name: Amul Stock Tracker

on:
  repository_dispatch:
    types: [ run-stock-check ]
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  track-stock:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        run: |
          # Check if PHP is already installed
          if ! command -v php &> /dev/null; then
            sudo apt update
            sudo apt install -y php php-cli php-curl php-json php-mbstring
          fi
          php --version

      - name: Run stock tracker
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: php tracker.php

      - name: Upload stock data as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: stock-data-${{ github.run_id }}
          path: |
            /home/*/stock-tracker-data/stock_data.json
            /home/*/stock-tracker-data/tracker.log
          retention-days: 3
